[package]
name = "buck2-nextest-executor"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false
rust-version = "1.88"

[lib]
path = "src/lib.rs"

[[bin]]
name = "nextest-v2-executor"
path = "src/main.rs"

[[bin]]
name = "nextest-v2-executor-fixture"
path = "src/fixture.rs"

[dependencies]
futures = { version = "=0.3.31", default-features = false, features = ["alloc", "async-await", "std"] }
hyper-util = { version = "=0.1.17", default-features = false, features = ["client", "client-legacy", "http1", "http2", "service", "tokio"] }
libc = "=0.2.189"
prost = "=0.14.4"
prost-types = "=0.14.4"
quick-xml = { version = "=0.37.5", default-features = false }
rustix = { version = "=0.38.44", default-features = false, features = ["fs", "use-libc", "linux_latest"] }
tokio = { version = "=1.52.3", default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
tokio-stream = { version = "=0.1.17", default-features = false, features = ["net"] }
tonic = { version = "=0.14.6", default-features = false, features = ["codegen", "router", "server", "transport"] }
tonic-prost = "=0.14.6"
tower = { version = "=0.5.2", default-features = false, features = ["util"] }

[dev-dependencies]
tempfile = "=3.13.0"
